# **Numpy**

In [1]:
import numpy as np

### 1. Arrays in NumPy

In [2]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

### 2. Array Creation

In [3]:
zeros_array = np.zeros((3, 3))
ones_array = np.ones((2, 2))
range_array = np.arange(0, 20, 2)

In [4]:
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
ones_array

array([[1., 1.],
       [1., 1.]])

In [6]:
range_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### 3. Array Indexing

In [7]:
arr1[2]

3

### 4. Array Slicing

In [8]:
arr1[1:4]

array([2, 3, 4])

### 5. Array Manipulation

In [9]:
np.reshape(range_array, (2, 5))

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

### 6. Universal Functions (ufunc)

In [10]:
added_arrays = np.add(arr1, 5)
added_arrays

array([ 6,  7,  8,  9, 10])

### 7. Broadcasting

In [11]:
broadcasted_array = arr1 + 3
broadcasted_array

array([4, 5, 6, 7, 8])

### 8. Linear Algebra in NumPy

In [12]:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
dot_product = np.dot(matrix_a, matrix_b)

In [13]:
matrix_a

array([[1, 2],
       [3, 4]])

In [14]:
matrix_b

array([[5, 6],
       [7, 8]])

In [15]:
dot_product

array([[19, 22],
       [43, 50]])

### 9. Random in NumPy

In [16]:
random_array = np.random.rand(3, 3)
random_array

array([[0.69026847, 0.45979494, 0.08727783],
       [0.11540099, 0.01767915, 0.1777267 ],
       [0.97295269, 0.81443425, 0.38588941]])

### 10. Fourier Transform in NumPy

In [17]:
signal = np.array([1, 2, 3, 4])
fourier_transform = np.fft.fft(signal)

In [18]:
fourier_transform

array([10.+0.j, -2.+2.j, -2.+0.j, -2.-2.j])